/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_claret_utils_StringUtils */

#ifndef _Included_org_claret_utils_StringUtils
#define _Included_org_claret_utils_StringUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_claret_utils_StringUtils
 * Method:    ltrim
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_claret_utils_StringUtils_ltrim
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_claret_utils_StringUtils
 * Method:    rtrim
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_claret_utils_StringUtils_rtrim
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
